spring:
  messages:
    basename: i18n/message
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingwei-wallet?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connection-test-query: SELECT 1

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: io.jingwei.wallet.biz.entity,io.jingwei.base.idgen.worker.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    enabled: true
    register-with-eureka: true


xxl:
  job:
    admin:
      # 地址为刚刚配置的调度中心的访问地址
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # 自定义appName（执行器名称）
      appname: xxl-job-wallet
      # ip 可以写 （程序跑在的机器ip上），也可以不写
      ip:
      port: 9999
      # 执行器日志文件存储路径
      logpath: /data/applogs/xxl-job/jobhandler
      # 设置日志过期时间  -1表示永不过期
      logretentiondays: 7
      accessToken: 123456


eth:
  sync:
    initialStartBlock: 5560182
    nodeName: testnet
    url:

  encrypt:
    key: ENC(CCs5sdzhs6MFh8fkQw3ultCBo3F9yhzh2RdNBIbSGqc=)
